!!Client_settings
engine:
  default: _start
graphics:
  font_height: 48
  font_name: ProFontWindows
  font_antialias: false
window:
  fullscreen: false
  height: 720
  title: USC Iggesund
  width: 1280
